numero_tabuada = int(input("Digite um número para ver sua tabuada: "))

print("==================")
print("{} x 1 = {}".format(numero_tabuada, numero_tabuada * 1))
print("{} x 2 = {}".format(numero_tabuada, numero_tabuada * 2))
print("{} x 3 = {}".format(numero_tabuada, numero_tabuada * 3))
print("{} x 4 = {}".format(numero_tabuada, numero_tabuada * 4))
print("{} x 5 = {}".format(numero_tabuada, numero_tabuada * 5))
print("{} x 6 = {}".format(numero_tabuada, numero_tabuada * 6))
print("{} x 7 = {}".format(numero_tabuada, numero_tabuada * 7))
print("{} x 8 = {}".format(numero_tabuada, numero_tabuada * 8))
print("{} x 9 = {}".format(numero_tabuada, numero_tabuada * 9))
print("{} x 10 = {}".format(numero_tabuada, numero_tabuada * 10))
print("==================")